remote_theme: pages-themes/hacker@v0.2.0

# attempt to fix lack of CSS rendering in deployed mode
baseurl: /vsearch
url: https://torognes.github.io

# keep literal double-hyphens in option names (e.g. --cluster_size)
# instead of letting kramdown turn them into en-dashes
kramdown:
  typographic_symbols:
    ndash: "--"
    mdash: "---"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
