/*

  VSEARCH: a versatile open source tool for metagenomics

  Copyright (C) 2014-2026, Torbjorn Rognes, Frederic Mahe and Tomas Flouri
  All rights reserved.

  Contact: Torbjorn Rognes <torognes@ifi.uio.no>,
  Department of Informatics, University of Oslo,
  PO Box 1080 Blindern, NO-0316 Oslo, Norway

  This software is dual-licensed and available under a choice
  of one of two licenses, either under the terms of the GNU
  General Public License version 3 or the BSD 2-Clause License.


  GNU General Public License version 3

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.


  The BSD 2-Clause License

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.

*/

#include "vsearch.hpp"
#include "commands/help.hpp"
#include "commands/version.hpp"  // show_publication
#include <array>
#include <cstddef>  // std::size_t
#include <cstdio>  // std::fprintf, std::fputs


  /*       0         1         2         3         4         5         6         7          */
  /*       01234567890123456789012345678901234567890123456789012345678901234567890123456789 */
  static constexpr std::size_t help_line_count = 492;
  static constexpr std::array<char const *, help_line_count> help_message =
    {{
      "\n",
      "For further details, please consult the manual by entering: man vsearch\n",
      "\n",
      "General options\n",
      "  --bzip2_decompress          decompress input with bzip2 (required if pipe)\n",
      "  --fasta_width INT           width of FASTA seq lines, 0 for no wrap (80)\n",
      "  --gzip_decompress           decompress input with gzip (required if pipe)\n",
      "  --help | -h                 display help information\n",
      "  --log FILENAME              write messages, timing and memory info to file\n",
      "  --maxseqlength INT          maximum sequence length (50000)\n",
      "  --minseqlength INT          min seq length (clust/derep/search: 32, other:1)\n",
      "  --no_progress               do not show progress indicator\n",
      "  --notrunclabels             do not truncate labels at first space\n",
      "  --quiet                     output just warnings and fatal errors to stderr\n",
      "  --threads INT               number of threads to use, zero for all cores (0)\n",
      "  --version | -v              display version information\n",
      "\n",
      "Chimera detection with new algorithm\n",
      "  --chimeras_denovo FILENAME  detect chimeras de novo in long exact sequences\n",
      " Parameters\n",
      "  --abskew REAL               minimum abundance ratio (1.0)\n",
      "  --chimeras_diff_pct REAL    mismatch % allowed in each chimeric region (0.0)\n",
      "  --chimeras_length_min INT   minimum length of each chimeric region (10)\n",
      "  --chimeras_parents_max INT  maximum number of parent sequences (3)\n",
      "  --chimeras_parts INT        number of parts to divide sequences (length/100)\n",
      "  --sizein                    propagate abundance annotation from input\n",
      " Output\n",
      "  --alignwidth INT            width of alignments in alignment output file (60)\n",
      "  --alnout FILENAME           output chimera alignments to file\n",
      "  --chimeras FILENAME         output chimeric sequences to file\n",
      "  --nonchimeras FILENAME      output non-chimeric sequences to file\n",
      "  --relabel STRING            relabel nonchimeras with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeout                   include abundance information when relabelling\n",
      "  --tabbedout FILENAME        output chimera info to tab-separated file\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "Chimera detection with UCHIME algorithms\n",
      "  --uchime_denovo FILENAME    detect chimeras de novo\n",
      "  --uchime2_denovo FILENAME   detect chimeras de novo in denoised amplicons\n",
      "  --uchime3_denovo FILENAME   detect chimeras de novo in denoised amplicons\n",
      "  --uchime_ref FILENAME       detect chimeras using a reference database\n",
      " Data\n",
      "  --db FILENAME               reference database for --uchime_ref\n",
      " Parameters\n",
      "  --abskew REAL               minimum abundance ratio (2.0, 16.0 for uchime3)\n",
      "  --dn REAL                   'no' vote pseudo-count (1.4)\n",
      "  --mindiffs INT              minimum number of differences in segment (3) *\n",
      "  --mindiv REAL               minimum divergence from closest parent (0.8) *\n",
      "  --minh REAL                 minimum score (0.28) * ignored in uchime2/3\n",
      "  --sizein                    propagate abundance annotation from input\n",
      "  --self                      exclude identical labels for --uchime_ref\n",
      "  --selfid                    exclude identical sequences for --uchime_ref\n",
      "  --xn REAL                   'no' vote weight (8.0)\n",
      " Output\n",
      "  --alignwidth INT            width of alignment in uchimealn output (80)\n",
      "  --borderline FILENAME       output borderline chimeric sequences to file\n",
      "  --chimeras FILENAME         output chimeric sequences to file\n",
      "  --fasta_score               include chimera score in FASTA output\n",
      "  --nonchimeras FILENAME      output non-chimeric sequences to file\n",
      "  --relabel STRING            relabel nonchimeras with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeout                   include abundance information when relabelling\n",
      "  --uchimealns FILENAME       output chimera alignments to file\n",
      "  --uchimeout FILENAME        output to chimera info to tab-separated file\n",
      "  --uchimeout5                make output compatible with uchime version 5\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "Clustering\n",
      "  --cluster_fast FILENAME     cluster sequences after sorting by length\n",
      "  --cluster_size FILENAME     cluster sequences after sorting by abundance\n",
      "  --cluster_smallmem FILENAME cluster already sorted sequences (see -usersort)\n",
      "  --cluster_unoise FILENAME   denoise Illumina amplicon reads\n",
      " Parameters (most searching options also apply)\n",
      "  --cons_truncate             do not ignore terminal gaps in MSA for consensus\n",
      "  --id REAL                   reject if identity lower, accepted values: 0-1.0\n",
      "  --iddef INT                 id definition, 0-4=CD-HIT,all,int,MBL,BLAST (2)\n",
      "  --qmask none|dust|soft      mask seqs with dust, soft or no method (dust)\n",
      "  --sizein                    propagate abundance annotation from input\n",
      "  --strand plus|both          cluster using plus or both strands (plus)\n",
      "  --usersort                  indicate sequences not pre-sorted by length\n",
      "  --minsize INT               minimum abundance (unoise only) (8)\n",
      "  --unoise_alpha REAL         alpha parameter (unoise only) (2.0)\n",
      " Output\n",
      "  --biomout FILENAME          filename for OTU table output in biom 1.0 format\n",
      "  --centroids FILENAME        output centroid sequences to FASTA file\n",
      "  --clusterout_id             add cluster id info to consout and profile files\n",
      "  --clusterout_sort           order msaout, consout, profile by decr abundance\n",
      "  --clusters STRING           output each cluster to a separate FASTA file\n",
      "  --consout FILENAME          output cluster consensus sequences to FASTA file\n",
      "  --mothur_shared_out FN      filename for OTU table output in mothur format\n",
      "  --msaout FILENAME           output multiple seq. alignments to FASTA file\n",
      "  --otutabout FILENAME        filename for OTU table output in classic format\n",
      "  --profile FILENAME          output sequence profile of each cluster to file\n",
      "  --relabel STRING            relabel centroids with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeorder                 sort accepted centroids by abundance, AGC\n",
      "  --sizeout                   write cluster abundances to centroid file\n",
      "  --centroid_sizeout          write centroid abundances to centroid file\n",
      "  --uc FILENAME               specify filename for UCLUST-like output\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "Convert SFF to FASTQ\n",
      "  --sff_convert FILENAME      convert given SFF file to FASTQ format\n",
      " Parameters\n",
      "  --sff_clip                  clip ends of sequences as indicated in file (no)\n",
      "  --fastq_asciiout INT        FASTQ output quality score ASCII base char (33)\n",
      "  --fastq_qmaxout INT         maximum base quality value for FASTQ output (41)\n",
      "  --fastq_qminout INT         minimum base quality value for FASTQ output (0)\n",
      " Output\n",
      "  --fastqout FILENAME         output converted sequences to given FASTQ file\n",
      "\n",
      "Dereplication and rereplication\n",
      "  --derep_fulllength FILENAME dereplicate sequences in the given FASTA file\n",
      "  --derep_id FILENAME         dereplicate using both identifiers and sequences\n",
      "  --derep_prefix FILENAME     dereplicate sequences in file based on prefixes\n",
      "  --derep_smallmem FILENAME   dereplicate sequences in file using less memory\n",
      "  --fastx_uniques FILENAME    dereplicate sequences in the FASTA/FASTQ file\n",
      "  --rereplicate FILENAME      rereplicate sequences in the given FASTA file\n",
      " Parameters\n",
      "  --maxuniquesize INT         maximum abundance for output from dereplication\n",
      "  --minuniquesize INT         minimum abundance for output from dereplication\n",
      "  --sizein                    propagate abundance annotation from input\n",
      "  --strand plus|both          dereplicate plus or both strands (plus)\n",
      " Output\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmaxout INT         maximum base quality value for FASTQ output (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --fastq_qminout INT         minimum base quality value for FASTQ output (0)\n",
      "  --fastaout FILENAME         output FASTA file (for fastx_uniques)\n",
      "  --fastqout FILENAME         output FASTQ file (for fastx_uniques)\n",
      "  --output FILENAME           output FASTA file (not for fastx_uniques)\n",
      "  --relabel STRING            relabel with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeout                   write abundance annotation to output\n",
      "  --tabbedout FILENAME        write cluster info to tsv file for fastx_uniques\n",
      "  --topn INT                  output only n most abundant sequences after derep\n",
      "  --uc FILENAME               filename for UCLUST-like dereplication output\n",
      "  --xsize                     strip abundance information in derep output\n",
      "\n",
      "FASTA to FASTQ conversion\n",
      "  --fasta2fastq FILENAME      convert from FASTA to FASTQ, fake quality scores\n",
      " Parameters\n",
      "  --fastq_asciiout INT        FASTQ output quality score ASCII base char (33)\n",
      "  --fastq_qmaxout INT         fake quality score for FASTQ output (41)\n",
      " Output\n",
      "  --fastqout FILENAME         FASTQ output filename for converted sequences\n",
      "\n",
      "FASTQ format conversion\n",
      "  --fastq_convert FILENAME    convert between FASTQ file formats\n",
      " Parameters\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_asciiout INT        FASTQ output quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmaxout INT         maximum base quality value for FASTQ output (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --fastq_qminout INT         minimum base quality value for FASTQ output (0)\n",
      " Output\n",
      "  --fastqout FILENAME         FASTQ output filename for converted sequences\n",
      "\n",
      "FASTQ format detection and quality analysis\n",
      "  --fastq_chars FILENAME      analyse FASTQ file for version and quality range\n",
      " Parameters\n",
      "  --fastq_tail INT            min length of tails to count for fastq_chars (4)\n",
      "\n",
      "FASTQ quality statistics\n",
      "  --fastq_stats FILENAME      report statistics on FASTQ file\n",
      "  --fastq_eestats FILENAME    quality score and expected error statistics\n",
      "  --fastq_eestats2 FILENAME   expected error and length cutoff statistics\n",
      " Parameters\n",
      "  --ee_cutoffs REAL,...       fastq_eestats2 expected error cutoffs (0.5,1,2)\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --length_cutoffs INT,INT,INT fastq_eestats2 length (min,max,incr) (50,*,50)\n",
      " Output\n",
      "  --log FILENAME              output file for fastq_stats statistics\n",
      "  --output FILENAME           output file for fastq_eestats(2) statistics\n",
      "\n",
      "Masking (new)\n",
      "  --fastx_mask FILENAME       mask sequences in the given FASTA or FASTQ file\n",
      " Parameters\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --hardmask                  mask by replacing with N instead of lower case\n",
      "  --max_unmasked_pct          max unmasked % of sequences to keep (100.0)\n",
      "  --min_unmasked_pct          min unmasked % of sequences to keep (0.0)\n",
      "  --qmask none|dust|soft      mask seqs with dust, soft or no method (dust)\n",
      " Output\n",
      "  --fastaout FILENAME         output to specified FASTA file\n",
      "  --fastqout FILENAME         output to specified FASTQ file\n",
      "\n",
      "Masking (old)\n",
      "  --maskfasta FILENAME        mask sequences in the given FASTA file\n",
      " Parameters\n",
      "  --hardmask                  mask by replacing with N instead of lower case\n",
      "  --qmask none|dust|soft      mask seqs with dust, soft or no method (dust)\n",
      " Output\n",
      "  --output FILENAME           output to specified FASTA file\n",
      "\n",
      "Orient sequences in forward or reverse direction\n",
      "  --orient FILENAME           orient sequences in given FASTA/FASTQ file\n",
      " Data\n",
      "  --db FILENAME               database of sequences in correct orientation\n",
      "  --dbmask none|dust|soft     mask db seqs with dust, soft or no method (dust)\n",
      "  --qmask none|dust|soft      mask query with dust, soft or no method (dust)\n",
      "  --wordlength INT            length of words used for matching 3-15 (12)\n",
      " Output\n",
      "  --fastaout FILENAME         FASTA output filename for oriented sequences\n",
      "  --fastqout FILENAME         FASTQ output filenamr for oriented sequences\n",
      "  --notmatched FILENAME       output filename for undetermined sequences\n",
      "  --tabbedout FILENAME        output filename for result information\n",
      "\n",
      "Paired-end reads joining\n",
      "  --fastq_join FILENAME       join paired-end reads into one sequence with gap\n",
      " Data\n",
      "  --reverse FILENAME          specify FASTQ file with reverse reads\n",
      "  --join_padgap STRING        sequence string used for padding (NNNNNNNN)\n",
      "  --join_padgapq STRING       quality string used for padding (IIIIIIII)\n",
      " Output\n",
      "  --fastaout FILENAME         FASTA output filename for joined sequences\n",
      "  --fastqout FILENAME         FASTQ output filename for joined sequences\n",
      "\n",
      "Paired-end reads synchronizing\n",
      "  --fastx_syncpairs FILENAME  reorder paired reads to match across both files\n",
      " Data\n",
      "  --reverse FILENAME          specify FASTA/FASTQ file with reverse reads\n",
      " Parameters\n",
      "  --read_separators STRING    characters preceding the mate number 1 or 2 (/)\n",
      " Output\n",
      "  --fastaout FILENAME         FASTA filename for synced forward reads\n",
      "  --fastaout_rev FILENAME     FASTA filename for synced reverse reads\n",
      "  --fastaout_orphans FN       FASTA filename for unpaired forward reads\n",
      "  --fastaout_orphans_rev FN   FASTA filename for unpaired reverse reads\n",
      "  --fastqout FILENAME         FASTQ filename for synced forward reads\n",
      "  --fastqout_rev FILENAME     FASTQ filename for synced reverse reads\n",
      "  --fastqout_orphans FN       FASTQ filename for unpaired forward reads\n",
      "  --fastqout_orphans_rev FN   FASTQ filename for unpaired reverse reads\n",
      "\n",
      "Paired-end reads merging\n",
      "  --fastq_mergepairs FILENAME merge paired-end reads into one sequence\n",
      " Data\n",
      "  --reverse FILENAME          specify FASTQ file with reverse reads\n",
      " Parameters\n",
      "  --fastq_allowmergestagger   allow merging of staggered reads\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_maxdiffpct REAL     maximum percentage diff. bases in overlap (100.0)\n",
      "  --fastq_maxdiffs INT        maximum number of different bases in overlap (10)\n",
      "  --fastq_maxee REAL          maximum expected error value for merged sequence\n",
      "  --fastq_maxmergelen         maximum length of entire merged sequence\n",
      "  --fastq_maxns INT           maximum number of N's\n",
      "  --fastq_minlen INT          minimum input read length after truncation (1)\n",
      "  --fastq_minmergelen         minimum length of entire merged sequence\n",
      "  --fastq_minovlen            minimum length of overlap between reads (10)\n",
      "  --fastq_nostagger           disallow merging of staggered reads (default)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmaxout INT         maximum base quality value for FASTQ output (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --fastq_qminout INT         minimum base quality value for FASTQ output (0)\n",
      "  --fastq_truncqual INT       base quality value for truncation\n",
      " Output\n",
      "  --eetabbedout FILENAME      output error statistics to specified file\n",
      "  --fastaout FILENAME         FASTA output filename for merged sequences\n",
      "  --fastaout_notmerged_fwd FN FASTA filename for non-merged forward sequences\n",
      "  --fastaout_notmerged_rev FN FASTA filename for non-merged reverse sequences\n",
      "  --fastq_eeout               include expected errors (ee) in FASTQ output\n",
      "  --fastqout FILENAME         FASTQ output filename for merged sequences\n",
      "  --fastqout_notmerged_fwd FN FASTQ filename for non-merged forward sequences\n",
      "  --fastqout_notmerged_rev FN FASTQ filename for non-merged reverse sequences\n",
      "  --label_suffix STRING       suffix to append to label of merged sequences\n",
      "  --xee                       remove expected errors (ee) info from output\n",
      "\n",
      "Pairwise alignment\n",
      "  --allpairs_global FILENAME  perform global alignment of all sequence pairs\n",
      " Output (most searching options also apply)\n",
      "  --alnout FILENAME           filename for human-readable alignment output\n",
      "  --acceptall                 output all pairwise alignments\n",
      "\n",
      "Restriction site cutting\n",
      "  --cut FILENAME              filename of FASTA formatted input sequences\n",
      " Parameters\n",
      "  --cut_pattern STRING        pattern to match with ^ and _ at cut sites\n",
      " Output\n",
      "  --fastaout FILENAME         FASTA filename for fragments on forward strand\n",
      "  --fastaout_rev FILENAME     FASTA filename for fragments on reverse strand\n",
      "  --fastaout_discarded FN     FASTA filename for non-matching sequences\n",
      "  --fastaout_discarded_rev FN FASTA filename for non-matching, reverse compl.\n",
      "\n",
      "Reverse complementation\n",
      "  --fastx_revcomp FILENAME    reverse-complement seqs in FASTA or FASTQ file\n",
      " Parameters\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      " Output\n",
      "  --fastaout FILENAME         FASTA output filename\n",
      "  --fastqout FILENAME         FASTQ output filename\n",
      "  --label_suffix STRING       label to append to identifier in the output\n",
      "\n",
      "Searching\n",
      "  --search_exact FILENAME     filename of queries for exact match search\n",
      "  --usearch_global FILENAME   filename of queries for global alignment search\n",
      " Data\n",
      "  --db FILENAME               FASTA or UDB database (only FASTA for search_exact)\n",
      " Parameters\n",
      "  --dbmask none|dust|soft     mask db with dust, soft or no method (dust)\n",
      "  --fulldp                    full dynamic programming alignment (always on)\n",
      "  --gapext STRING             penalties for gap extension (2I/1E)\n",
      "  --gapopen STRING            penalties for gap opening (20I/2E)\n",
      "  --hardmask                  mask by replacing with N instead of lower case\n",
      "  --id REAL                   reject if identity lower\n",
      "  --iddef INT                 id definition, 0-4=CD-HIT,all,int,MBL,BLAST (2)\n",
      "  --idprefix INT              reject if first n nucleotides do not match\n",
      "  --idsuffix INT              reject if last n nucleotides do not match\n",
      "  --lca_cutoff REAL           fraction of matching hits required for LCA (1.0)\n",
      "  --leftjust                  reject if terminal gaps at alignment left end\n",
      "  --match INT                 score for match (2)\n",
      "  --maxaccepts INT            number of hits to accept and show per strand (1)\n",
      "  --maxdiffs INT              reject if more substitutions or indels\n",
      "  --maxgaps INT               reject if more indels\n",
      "  --maxhits INT               maximum number of hits to show (unlimited)\n",
      "  --maxid REAL                reject if identity higher\n",
      "  --maxqsize INT              reject if query abundance larger\n",
      "  --maxqt REAL                reject if query/target length ratio higher\n",
      "  --maxrejects INT            number of non-matching hits to consider (32)\n",
      "  --maxsizeratio REAL         reject if query/target abundance ratio higher\n",
      "  --maxsl REAL                reject if shorter/longer length ratio higher\n",
      "  --maxsubs INT               reject if more substitutions\n",
      "  --mid REAL                  reject if percent identity lower, ignoring gaps\n",
      "  --mincols INT               reject if alignment length shorter\n",
      "  --minqt REAL                reject if query/target length ratio lower\n",
      "  --minsizeratio REAL         reject if query/target abundance ratio lower\n",
      "  --minsl REAL                reject if shorter/longer length ratio lower\n",
      "  --mintsize INT              reject if target abundance lower\n",
      "  --minwordmatches INT        minimum number of word matches required (12)\n",
      "  --mismatch INT              score for mismatch (-4)\n",
      "  --n_mismatch                consider aligning with N's as mismatches\n",
      "  --pattern STRING            option is ignored\n",
      "  --qmask none|dust|soft      mask query with dust, soft or no method (dust)\n",
      "  --query_cov REAL            reject if fraction of query seq. aligned lower\n",
      "  --rightjust                 reject if terminal gaps at alignment right end\n",
      "  --sizein                    propagate abundance annotation from input\n",
      "  --self                      reject if labels identical\n",
      "  --selfid                    reject if sequences identical\n",
      "  --slots INT                 option is ignored\n",
      "  --strand plus|both          search plus or both strands (plus)\n",
      "  --target_cov REAL           reject if fraction of target seq. aligned lower\n",
      "  --weak_id REAL              include aligned hits with >= id; continue search\n",
      "  --wordlength INT            length of words for database index 3-15 (8)\n",
      " Output\n",
      "  --alnout FILENAME           filename for human-readable alignment output\n",
      "  --biomout FILENAME          filename for OTU table output in biom 1.0 format\n",
      "  --blast6out FILENAME        filename for blast-like tab-separated output\n",
      "  --dbmatched FILENAME        FASTA file for matching database sequences\n",
      "  --dbnotmatched FILENAME     FASTA file for non-matching database sequences\n",
      "  --fastapairs FILENAME       FASTA file with pairs of query and target\n",
      "  --lcaout FILENAME           output LCA of matching sequences to file\n",
      "  --matched FILENAME          FASTA file for matching query sequences\n",
      "  --mothur_shared_out FN      filename for OTU table output in mothur format\n",
      "  --notmatched FILENAME       FASTA file for non-matching query sequences\n",
      "  --otutabout FILENAME        filename for OTU table output in classic format\n",
      "  --output_no_hits            output non-matching queries to output files\n",
      "  --rowlen INT                width of alignment lines in alnout output (64)\n",
      "  --samheader                 include a header in the SAM output file\n",
      "  --samout FILENAME           filename for SAM format output\n",
      "  --sizeout                   write abundance annotation to dbmatched file\n",
      "  --top_hits_only             output only hits with identity equal to the best\n",
      "  --uc FILENAME               filename for UCLUST-like output\n",
      "  --uc_allhits                show all, not just top hit with uc output\n",
      "  --userfields STRING         fields to output in userout file\n",
      "  --userout FILENAME          filename for user-defined tab-separated output\n",
      "\n",
      "Shuffling and sorting\n",
      "  --shuffle FILENAME          shuffle order of sequences in FASTA file randomly\n",
      "  --sortbylength FILENAME     sort sequences by length in given FASTA file\n",
      "  --sortbysize FILENAME       abundance sort sequences in given FASTA file\n",
      " Parameters\n",
      "  --maxsize INT               maximum abundance for sortbysize\n",
      "  --minsize INT               minimum abundance for sortbysize\n",
      "  --randseed INT              seed for PRNG, zero to use random data source (0)\n",
      "  --sizein                    propagate abundance annotation from input\n",
      " Output\n",
      "  --output FILENAME           output to specified FASTA file\n",
      "  --relabel STRING            relabel sequences with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeout                   include abundance information when relabelling\n",
      "  --topn INT                  output just first n sequences\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "Subsampling\n",
      "  --fastx_subsample FILENAME  subsample sequences from given FASTA/FASTQ file\n",
      " Parameters\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --randseed INT              seed for PRNG, zero to use random data source (0)\n",
      "  --sample_pct REAL           sampling percentage between 0.0 and 100.0\n",
      "  --sample_size INT           sampling size\n",
      "  --sizein                    consider abundance info from input, do not ignore\n",
      " Output\n",
      "  --fastaout FILENAME         output subsampled sequences to FASTA file\n",
      "  --fastaout_discarded FILE   output non-subsampled sequences to FASTA file\n",
      "  --fastqout FILENAME         output subsampled sequences to FASTQ file\n",
      "  --fastqout_discarded        output non-subsampled sequences to FASTQ file\n",
      "  --relabel STRING            relabel sequences with this prefix string\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel with md5 digest of normalized sequence\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel with sha1 digest of normalized sequence\n",
      "  --sizeout                   update abundance information in output\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "Taxonomic classification\n",
      "  --sintax FILENAME           classify sequences in given FASTA/FASTQ file\n",
      " Parameters\n",
      "  --db FILENAME               taxonomic reference db in given FASTA or UDB file\n",
      "  --randseed INT              seed for PRNG, zero to use random data source (0)\n",
      "  --sintax_cutoff REAL        confidence value cutoff level (0.0)\n",
      "  --sintax_random             use random sequence, not shortest, if equal match\n",
      " Output\n",
      "  --tabbedout FILENAME        write results to given tab-delimited file\n",
      "\n",
      "Trimming and filtering\n",
      "  --fastx_filter FILENAME     trim and filter sequences in FASTA/FASTQ file\n",
      "  --fastq_filter FILENAME     trim and filter sequences in FASTQ file\n",
      "  --reverse FILENAME          FASTQ file with other end of paired-end reads\n",
      " Parameters\n",
      "  --fastq_ascii INT           FASTQ input quality score ASCII base char (33)\n",
      "  --fastq_maxee REAL          discard if expected error value is higher\n",
      "  --fastq_maxee_rate REAL     discard if expected error rate is higher\n",
      "  --fastq_maxlen INT          discard if length of sequence is longer\n",
      "  --fastq_maxns INT           discard if number of N's is higher\n",
      "  --fastq_minlen INT          discard if length of sequence is shorter\n",
      "  --fastq_minqual INT         discard if any base quality value lower (0)\n",
      "  --fastq_qmax INT            maximum base quality value for FASTQ input (41)\n",
      "  --fastq_qmin INT            minimum base quality value for FASTQ input (0)\n",
      "  --fastq_stripleft INT       delete given number of bases from the 5' end\n",
      "  --fastq_stripright INT      delete given number of bases from the 3' end\n",
      "  --fastq_truncee REAL        truncate to given maximum expected error\n",
      "  --fastq_truncee_rate REAL   truncate to given maximum expected error rate\n",
      "  --fastq_trunclen INT        truncate to given length (discard if shorter)\n",
      "  --fastq_trunclen_keep INT   truncate to given length (keep if shorter)\n",
      "  --fastq_truncqual INT       truncate to given minimum base quality\n",
      "  --maxsize INT               discard if abundance of sequence is above\n",
      "  --minsize INT               discard if abundance of sequence is below\n",
      " Output\n",
      "  --eeout                     include expected errors in output\n",
      "  --fastaout FN               FASTA filename for passed sequences\n",
      "  --fastaout_discarded FN     FASTA filename for discarded sequences\n",
      "  --fastaout_discarded_rev FN FASTA filename for discarded reverse sequences\n",
      "  --fastaout_rev FN           FASTA filename for passed reverse sequences\n",
      "  --fastqout FN               FASTQ filename for passed sequences\n",
      "  --fastqout_discarded FN     FASTQ filename for discarded sequences\n",
      "  --fastqout_discarded_rev FN FASTQ filename for discarded reverse sequences\n",
      "  --fastqout_rev FN           FASTQ filename for passed reverse sequences\n",
      "  --relabel STRING            relabel filtered sequences with given prefix\n",
      "  --relabel_keep              keep the old label after the new when relabelling\n",
      "  --relabel_md5               relabel filtered sequences with md5 digest\n",
      "  --relabel_self              relabel with the sequence itself as label\n",
      "  --relabel_sha1              relabel filtered sequences with sha1 digest\n",
      "  --sizeout                   include abundance information when relabelling\n",
      "  --xee                       remove expected errors (ee) info from output\n",
      "  --xsize                     strip abundance information in output\n",
      "\n",
      "UDB files\n",
      "  --makeudb_usearch FILENAME  make UDB file from given FASTA file\n",
      "  --udb2fasta FILENAME        output FASTA file from given UDB file\n",
      "  --udbinfo FILENAME          show information about UDB file\n",
      "  --udbstats FILENAME         report statistics about indexed words in UDB file\n",
      " Parameters\n",
      "  --dbmask none|dust|soft     mask db with dust, soft or no method (dust)\n",
      "  --hardmask                  mask by replacing with N instead of lower case\n",
      "  --wordlength INT            length of words for database index 3-15 (8)\n",
      " Output\n",
      "  --output FILENAME           UDB or FASTA output file\n",
    }};


auto help(struct Parameters const & parameters) -> void {
  if (parameters.opt_quiet) { return ; }

  show_publication();

  std::fprintf(stdout,
          "Usage: %s [OPTIONS]\n", parameters.progname);

  for (char const * const line : help_message)
    {
      std::fputs(line, stdout);
    }
}


auto help_message_line_count() -> std::size_t
{
  return help_message.size();
}


auto help_message_line(std::size_t const index) -> char const *
{
  return help_message[index];
}
