FROM fedora:latest
WORKDIR /opt/vsearch
COPY . .
RUN yum update -y
RUN yum -y install \
    bzip2-devel \
    gcc-c++ \
    make \
    simde-devel \
    zlib-devel
RUN make clean
RUN make CFLAGS="-O2" CXXFLAGS="-O2"
RUN make install
ENTRYPOINT ["/usr/local/bin/vsearch"]
