FROM debian:latest
WORKDIR /opt/vsearch
COPY . .
RUN apt-get update
RUN apt-get -y install \
    g++ \
    libbz2-dev \
    libsimde-dev \
    make \
    zlib1g-dev
RUN make clean
RUN make CFLAGS="-O2" CXXFLAGS="-O2"
RUN make install
ENTRYPOINT ["/usr/local/bin/vsearch"]
