# VSEARCH: a versatile open source tool for metagenomics
#
# Copyright (C) 2014-2015, Torbjorn Rognes, Frederic Mahe and Tomas Flouri
# All rights reserved.
#
# Contact: Torbjorn Rognes <torognes@ifi.uio.no>,
# Department of Informatics, University of Oslo,
# PO Box 1080 Blindern, NO-0316 Oslo, Norway
#
# This software is dual-licensed and available under a choice
# of one of two licenses, either under the terms of the GNU
# General Public License version 3 or the BSD 2-Clause License.
#
#
# GNU General Public License version 3
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# The BSD 2-Clause License
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# Profiling
#PROFILING=-g -fprofile-arcs -ftest-coverage
#PROFILING=-g -pg
PROFILING=-g

# Compiler warnings
WARN=-Wall -Wsign-compare
#WARN=-Weverything

CXX=g++
CXXFLAGS=-O3 -DHAVE_BZLIB -msse2 -mtune=core2 -Icityhash $(WARN) $(PROFILING)
LINKFLAGS=$(PROFILING)
LIBS=-lpthread -lssl -lcrypto -lbz2

PROG=vsearch-bz

OBJS=cityhash/city.o \
	abundance.o \
	align.o \
	align_simd.o \
	arch.o \
	bitmap.o \
	chimera.o \
	cluster.o \
	cpu_sse2.o \
	cpu_ssse3.o \
	db.o \
	dbindex.o \
	derep.o \
	maps.o \
	mask.o \
	minheap.o \
	msa.o \
	results.o \
	search.o \
	searchcore.o \
	showalign.o \
	shuffle.o \
	sortbylength.o \
	sortbysize.o \
	unique.o \
	userfields.o \
	util.o \
	vsearch.o \
	allpairs.o \
	linmemalign.o \
	subsample.o \
	fastqops.o \
	fasta.o \
	fastq.o \
	fastxdetect.o

DEPS=Makefile.BZLIB \
	cityhash/city.h \
	cityhash/config.h \
	abundance.h \
	align.h \
	align_simd.h \
	allpairs.h \
	arch.h \
	bitmap.h \
	chimera.h \
	cluster.h \
	cpu.h \
	db.h \
	dbindex.h \
	derep.h \
	fasta.h \
	fastq.h \
	fastqops.h \
	fastxdetect.h \
	linmemalign.h \
	maps.h \
	mask.h \
	minheap.h \
	msa.h \
	results.h \
	search.h \
	searchcore.h \
	showalign.h \
	shuffle.h \
	sortbylength.h \
	sortbysize.h \
	subsample.h \
	unique.h \
	userfields.h \
	util.h \
	vsearch.h \
	xstring.h 

.SUFFIXES:.o .cc

%.o : %.cc $(DEPS)
	$(CXX) $(CXXFLAGS) -c -o $@ $<

all : $(PROG)

vsearch-bz : $(OBJS)
	$(CXX) $(LINKFLAGS) -o $@ $(OBJS) $(LIBS)

clean :
	rm -f *~ $(OBJS) *.{S,gcda,gcno,gcov} $(PROG) gmon.out cityhash/*.{S,gcda,gcno,gcov}

cpu_ssse3.o : cpu.cc $(DEPS)
	$(CXX) $(CXXFLAGS) -mssse3 -DSSSE3 -c -o $@ $<

cpu_sse2.o : cpu.cc $(DEPS)
	$(CXX) $(CXXFLAGS) -c -o $@ $<
